services:

    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: php:8.1-fpm
        volumes:
            - ./code:/code
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
        #ports:
            #- "3307:3306"

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080